name: "Terraform Destroy"

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Escribe "yes" para confirmar la destruccion de la infraestructura'
        required: true
        type: string

env:
  TF_VAR_email_sns:           ${{ secrets.EMAIL_SNS }}
  TF_VAR_db_root_password:    ${{ secrets.DB_ROOT_PASSWORD }}
  TF_VAR_db_password:         ${{ secrets.DB_PASSWORD }}
  TF_VAR_owner_name:          ${{ secrets.OWNER_NAME }}
  TF_VAR_backup_iam_role_arn: ${{ secrets.BACKUP_IAM_ROLE_ARN }}

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'yes'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials (AWS Academy Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./environments/dev
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./environments/dev
        run: terraform destroy -auto-approve
